name: EPG 稳定更新
on:
  schedule:
    # 北京时间 04:50 执行（UTC 20:50）
    - cron: '50 20 * * *'
    # 北京时间 10:20 执行（UTC 02:20）
    - cron: '20 2 * * *'
    # 北京时间 16:20 执行（UTC 08:20）
    - cron: '20 8 * * *'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: 设为北京时间
        run: |
          sudo timedatectl set-timezone Asia/Shanghai
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v6
        with:
          python-version: '3.10'
      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install requests lxml
      - name: 生成EPG
        run: python epg.py
      - name: 提交
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add output/epg.gz
          git commit -m "EPG $(date +%F)" || echo "no changes"
          git push
